# Generated by Django 4.0.3 on 2024-06-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('juggling_score', models.FloatField()),
                ('speed_score', models.FloatField()),
                ('agility_score', models.FloatField()),
                ('dribbling_score', models.FloatField()),
                ('total_score', models.FloatField(default=0, editable=False)),
            ],
        ),
    ]
